# Generated by Django 2.2.13 on 2021-03-21 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('company_type', models.CharField(blank=True, max_length=255, null=True)),
                ('revenue', models.CharField(blank=True, max_length=255, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=255, null=True)),
                ('founded', models.DateField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scraped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('employee_status', models.CharField(max_length=255)),
                ('review_title', models.CharField(max_length=255)),
                ('helpful', models.IntegerField()),
                ('pros', models.TextField(blank=True, null=True)),
                ('cons', models.TextField(blank=True, null=True)),
                ('advice_to_management', models.TextField(blank=True, null=True)),
                ('rating_overall', models.FloatField()),
                ('rating_balance', models.IntegerField()),
                ('rating_culture', models.IntegerField()),
                ('rating_career', models.IntegerField()),
                ('rating_compensation', models.IntegerField()),
                ('rating_management', models.IntegerField()),
                ('recommends', models.BooleanField()),
                ('outlook', models.CharField(max_length=50)),
                ('approves_of_CEO', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('scraped_at_ts', models.DateTimeField(blank=True, default=None, null=True)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('cause', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('currently_here', models.BooleanField(blank=True, null=True)),
                ('profile', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('endorsements', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('average_total_pay', models.CharField(max_length=255)),
                ('base_pay', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_pay', models.CharField(blank=True, max_length=255, null=True)),
                ('based_on', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('recipient_profile', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_profile', to='api.Profile')),
                ('recommender_profile', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='recommender_profile', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='general', max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('data', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField(default=0)),
                ('currently_here', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Competitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='api.Company')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor', to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.TextField(blank=True, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
    ]
