# Generated by Django 2.2.13 on 2021-03-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210304_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linked_url',
            new_name='linkedin_url',
        ),
    ]
