# Generated by Django 2.2.13 on 2021-03-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_specialties'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialties',
            new_name='Specialty',
        ),
    ]
