# Generated by Django 2.2.13 on 2021-03-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210304_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='accomplishments',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='volunteer_experiences',
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='profile',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='certification',
            name='profile',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='interest',
            name='profile',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='profile',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='volunteer_experience',
            name='profile',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
