# Generated by Django 2.2.13 on 2021-03-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210304_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteer_experience',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
