# Generated by Django 2.2.13 on 2021-03-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210321_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company',
        ),
    ]
