# Generated by Django 2.2.13 on 2021-03-05 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210304_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='received',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='recommender_title',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='recommender_url',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recipient_profile',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_profile', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommender_profile',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='recommender_profile', to='api.Profile'),
        ),
    ]
