# Generated by Django 2.2.13 on 2021-03-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_experience_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
        ),
    ]
