# Generated by Django 2.2.13 on 2021-03-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210305_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='duration_months',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='volunteer_experience',
            old_name='duration_months',
            new_name='duration',
        ),
    ]
