# Generated by Django 2.2.13 on 2021-03-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210305_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='currently_here',
            field=models.BooleanField(default=False),
        ),
    ]
