# Generated by Django 2.2.13 on 2021-03-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_experience_currently_here'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
