# Generated by Django 2.2.13 on 2021-03-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210305_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.TextField(),
        ),
    ]
