# Generated by Django 2.2.13 on 2021-03-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210305_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('employee_status', models.CharField(max_length=255)),
                ('review_title', models.CharField(max_length=255)),
                ('helpful', models.IntegerField()),
                ('pros', models.TextField(blank=True, null=True)),
                ('cons', models.TextField(blank=True, null=True)),
                ('advice_to_management', models.TextField(blank=True, null=True)),
                ('rating_overall', models.FloatField()),
                ('rating_balance', models.IntegerField()),
                ('rating_culture', models.IntegerField()),
                ('rating_career', models.IntegerField()),
                ('rating_compensation', models.IntegerField()),
                ('rating_management', models.IntegerField()),
                ('recommends', models.BooleanField()),
                ('outlook', models.CharField(max_length=50)),
                ('approves_of_CEO', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='founded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='headquarters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='revenue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('average_total_pay', models.IntegerField()),
                ('base_pay', models.IntegerField()),
                ('additional_pay', models.IntegerField()),
                ('sample_size', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='general', max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('data', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Competitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='api.Company')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor', to='api.Company')),
            ],
        ),
    ]
