# Generated by Django 2.2.13 on 2021-03-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='based_on',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
