# Generated by Django 2.2.13 on 2021-03-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_salary_based_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='sample_size',
        ),
        migrations.AlterField(
            model_name='salary',
            name='additional_pay',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salary',
            name='average_total_pay',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_pay',
            field=models.CharField(max_length=255),
        ),
    ]
