# Generated by Django 2.2.13 on 2021-03-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210313_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
