# Generated by Django 2.2.13 on 2021-03-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_salary_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='additional_pay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_pay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
