# Generated by Django 2.2.13 on 2021-03-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='accomplishments',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='volunteer_experiences',
        ),
        migrations.DeleteModel(
            name='Accomplishment',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Volunteer_experience',
        ),
    ]
